# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 367903b2e28c24a7cc273ff9e814831307ea833673db27189cfa524e08828964b895fd2b819ed48e3b8a590dc38c60bd7db0a774e18f020a3566578649e0189b

test:
  secret_key_base: 101d3c411a7450142a6e54ed32f0590406e6332c0c81652dbe2333c0acdca94210aed9a9e580c79e5deeae2f67661571e08288a6ad31e90fecf885d5ebbcbb90

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
